//! Example community node: **uppercase**.
//!
//! Uppercases one text field on every input item. It is the smallest thing that shows the
//! whole shape of a Rust node — a contract, a config field for the UI, and the logic —
//! with zero ABI code. Read `nodes/rust/HOW_TO_WRITE_A_NODE.md` alongside it.
//!
//! This entire file is what an author writes. The `alloc`/`run`/`describe`/`memory`
//! exports the engine sandbox calls are generated by `export_node!` at the bottom.

use workflow_node::{
    export_node, ConfigField, DataField, FieldType, Input, Manifest, Node, NodeError, Output,
    Value, Widget,
};

/// The node. A unit struct: it holds no state — every per-run value arrives in [`Input`]
/// (`export_node!` constructs it as `Uppercase::default()` per invocation).
#[derive(Default)]
struct Uppercase;

/// The config field name selecting WHICH field to uppercase. Defaulting keeps the node
/// usable with no configuration at all.
const FIELD_CONFIG: &str = "field";
const DEFAULT_FIELD: &str = "text";

impl Node for Uppercase {
    /// (1) input contract, (2) output contract, (3) UI/config — all declared here.
    fn manifest(&self) -> Manifest {
        Manifest::new("uppercase", "Uppercase", "1.0.0")
            .with_description("Uppercases a chosen text field on every item.")
            .with_icon("type")
            .with_tags(&["transform", "tools", "text"])
            .with_config(vec![ConfigField::new(
                FIELD_CONFIG,
                FieldType::String,
                Widget::TextField,
                false,
                "Name of the field to uppercase (default: text)",
            )])
            .with_input(vec![DataField::new("text", FieldType::String)])
            .with_output(vec![DataField::new("text", FieldType::String)])
    }

    /// (4) the logic. Uppercase the chosen field on each item; pass items whose field is
    /// missing or non-string through unchanged (a per-item shape mismatch is not a node
    /// failure — same rule the core `filter` node follows).
    fn run(&self, input: Input) -> Result<Output, NodeError> {
        let field = input.config_str(FIELD_CONFIG).unwrap_or(DEFAULT_FIELD).to_string();

        let out = input
            .items
            .into_iter()
            .map(|mut item| {
                if let Some(Value::String(s)) = item.get(&field) {
                    let upper = Value::String(s.to_uppercase());
                    if let Some(obj) = item.as_object_mut() {
                        obj.insert(field.clone(), upper);
                    }
                }
                item
            })
            .collect();

        Ok(Output::items(out))
    }
}

export_node!(Uppercase);
